name: Run Dify API Regularly

on:
  # 毎日0時 (UTC) に実行します (日本時間の午前9時)
  schedule:
    - cron: '0 0 * * *'
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  call-dify-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Dify API
        run: |
          curl -X POST 'https://api.dify.ai/v1/workflows/run' \
              --header 'Authorization: Bearer ${{ secrets.DIFY_API_KEY }}' \
              --header 'Content-Type: application/json' \
              --data-raw '{
                  "inputs": {},
                  "response_mode": "streaming",
                  "user": "abc-123"
              }'
